#Les mots et les indices liés à ces mêmes mots ont été générés par une IA.
#Le dictionnaire ci-dessous recense les différents mots disponibles pour le pendu ; ils sont classés par thème et par nombre de lettres dans le mot.

dictionnaire_des_mots = {

  
    "ANIMAUX": {           

        "4_6": {
            "AIGLE":  "Rapace aux serres redoutables",
            "PANDA":  "Ours asiatique en noir et blanc",
            "LION":   "Male a criniere, souverain de la savane",
            "TIGRE":  "Felin orange aux rayures noires",
            "KOALA":  "Dormeur accro aux feuilles d'eucalyptus",
            "HIBOU":  "Chasseur silencieux de la nuit",
            "MEDUSE": "Corps translucide et filaments urticants",
            "TORTUE": "Carapace et longevite record",
            "ZEBRE":  "Equide africain au patron unique",
            "LOUP":   "Predateur social des forets froides",
            "CERF":   "Ramure qui tombe et repousse chaque annee",
            "LYNX":   "Felin sauvage aux oreilles a pinceau",
            "MORSE":  "Defenses de glace sur banquise arctique",
            "BISON":  "Grand bovin sauvage des grandes plaines",
            "LAPIN":  "C'est un rongeur bondissant",
            "REQUIN": "Predateur bleu aux dents en rangees",
            "LOUTRE": "Glisse sur le dos en craquant des coquillages",
        },

        "7_10": {
            "ELEPHANT":  "Le plus massif des terrestres",
            "DAUPHIN":   "Mammifere marin au sonar naturel",
            "GORILLE":   "Primate africain au regard intense",
            "PINGOUIN":  "Oiseau des glaces qui se dandine",
            "PAPILLON":  "Metamorphose d'une chenille",
            "ABEILLE":   "Pollinisatrice indispensable aux recoltes",
            "SERPENT":   "Reptile qui avale sa proie entiere",
            "BALEINE":   "Mammifere aux chants sous-marins",
            "FLAMANT":   "Couleur liee a son regime alimentaire",
            "PERROQUET": "Mimique vocale en plumage colore",
            "PIEUVRE":   "Huit bras et tres haute intelligence",
            "GUEPARD":   "Acceleration foudroyante sur courte distance",
            "VAUTOUR":   "Nettoyeur de carcasses dans le ciel",
            "SCORPION":  "Arachnide dont la queue frappe en premier",
            "MANCHOT":   "Plongeur des regions polaires en smoking",
            "CHOUETTE":  "Tournage de tete a 270 degres",
            "PIRANHA":   "Banc de petits poissons aux dents acerees",
        },

        "11_et_plus": {
            "HIPPOPOTAME":           "Poids lourd territorial des rivieres",
            "KANGOUROU ROUGE":       "Marsupial geant du desert australien",
            "GRENOUILLE ARBORICOLE": "Amphibien minuscule aux ventouses adhesives",
            "CROCODILE DU NIL":      "Embuscade depuis les berges du grand fleuve",
            "ARAIGNEE SAUTEUSE":     "Predatrice aux yeux multiples et immenses",
            "AUTRUCHE D'AFRIQUE":    "La plus grande et la plus rapide a pied",
            "CAMELEON JACKSON":      "Trois cornes et camouflage spectaculaire",
            "SANGLIER D'EUROPE":     "Boutoir tranchant et groupe familial",
            "HERISSON COMMUN":       "Boule de piquants au moindre danger",
            "SCARABEE SACRE":        "Insecte divinise qui roule une boule",
            "TARENTULE NOIRE":       "Grande velue aux crochets venimeux",
            "RHINOCEROS BLANC":      "Cuirasse de peau et corne menacee",
            "GIRAFE RETICULEE":      "Patron geometrique unique sur chaque individu",
            "FOURMI LEGIONNAIRE":    "Colonne devastatrice de millions d'individus",
            "JAGUAR MELANISTE":      "Grand felin noir presque invisible",
            "VARAN DE KOMODO":       "Plus grand lezard du monde aux dents bacteriennes",
            "MANTE RELIGIEUSE":      "Insecte predateur qui semble en priere",
        },
    },

    "FILMS": {           

        "4_6": {
            "AVATAR": "Humanite contre nature sur une lune distante",
            "MATRIX": "Pilule rouge ou pilule bleue",
            "JOKER":  "La descente d'un homme invisible",
            "SHREK":  "Un ogre contrarie d'avoir des visiteurs",
            "ROCKY":  "Un inconnu monte sur le ring du champion",
            "ALIEN":  "Quelque chose a survecu a bord",
            "LUPIN":  "Cambrioleur moderne au Louvre",
            "NARCOS": "L'ascension et la traque d'un cartel",
            "OZARK":  "Blanchiment en famille dans le Missouri",
            "LOST":   "Survivants d'un crash sur une ile etrange",
            "DEXTER": "Tueur en serie qui traque les tueurs en serie",
            "DARK":   "Tunnel temporel dans un village allemand",
            "DUNE":   "Planete de sable et epice rare",
            "SUITS":  "Cabinet d'avocats new-yorkais et imposteur",
            "ROME":   "Serie sur la chute de la republique romaine",
            "BONES":  "Anthropologue et agent FBI resolvent des crimes",
            "MONK":   "Detektive prodige aux nombreuses phobies",
        },

        "7_10": {
            "TITANIC":     "Un paquebot, un iceberg, une histoire d'amour",
            "INCEPTION":   "Voler des secrets au coeur du sommeil",
            "PARASITE":    "Deux familles, un sous-sol, un secret",
            "GLADIATOR":   "Un general trahi retourne au sable",
            "PSYCHOSE":    "Un motel isole et une douche fatale",
            "SCARFACE":    "La Floride, la poudre blanche et la chute",
            "TERMINATOR":  "Une machine envoyee pour changer le passe",
            "AMADEUS":     "La jalousie d'un compositeur de cour",
            "LE ROI LION": "Un lionceau, une trahison, un destin",
            "STAR WARS":   "Galaxie lointaine, sabre laser, cote obscur",
            "THE OFFICE":  "Camera-verite dans un bureau quelconque",
            "FRIENDS":     "Six New-Yorkais et un canape orange",
            "SQUID GAME":  "Jeux d'enfants a enjeux mortels",
            "THE WITCHER": "Un chasseur de monstres aux yeux de loup",
            "VIKINGS":     "Longboats, pillages et Valhalla",
            "THE CROWN":   "Le poids discret d'une couronne",
            "CHERNOBYL":   "Reconstitution d'une catastrophe nucleaire sovietique",
        },
 
        "11_et_plus": {
            "INTERSTELLAR":     "Wormhole et relativite pour sauver l'humanite",
            "LES AFFRANCHIS":   "La mafia new-yorkaise vue de l'interieur",
            "PULP FICTION":     "Histoires criminelles melees a Los Angeles",
            "AMELIE POULAIN":   "Une Parisienne qui arrange la vie des autres",
            "FORREST GUMP":     "Un homme simple traverse un siecle",
            "JURASSIC PARK":    "Des reptiles d'un autre temps liberes",
            "HARRY POTTER":     "Lettre a l'encre invisible a onze ans",
            "GAME OF THRONES":  "Trones, dragons et trahisons en Westeros",
            "BREAKING BAD":     "Un diagnostic qui change tout",
            "STRANGER THINGS":  "Dimension parallele dans une ville ordinaire",
            "LA CASA DE PAPEL": "Combinaisons rouges et masques de Dali",
            "PEAKY BLINDERS":   "Casquettes, rasoirs et Birmingham d'apres-guerre",
            "BLACK MIRROR":     "Et si la technologie se retournait contre nous",
            "HOUSE OF CARDS":   "L'ambition politique sans limite a Washington",
            "TRUE DETECTIVE":   "Enquete sur des crimes rituels dans le bayou",
            "BAND OF BROTHERS": "Une compagnie americaine du D-Day au Rhin",
            "DOWNTON ABBEY":    "La vie d'un manoir anglais entre deux guerres",
        },
    },

    "PERSONNAGES": {           

        "4_6": {
            "DARWIN": "Voyage aux Galapagos, theorie controversee",
            "MOZART": "Opera compose a l'age de quatorze ans",
            "FREUD":  "Divan, inconscient et reves analyses",
            "PELE":   "Trois Coupes du Monde, Santos toute sa carriere",
            "PLATON": "Philosophe grec de l'Academie",
            "HOMERE": "Aede grec auteur de deux epopees fondatrices",
            "DALI":   "Montres molles et paranoia critique",
            "MONET":  "Serie de nympheas en plein air",
            "RODIN":  "Sculpteur du Penseur et du Baiser",
            "CAMUS":  "Absurde, soleil algerien et Nobel",
            "KAFKA":  "Metamorphose en insecte et labyrinthes bureaucratiques",
            "MARX":   "Manifeste et Capital, theorie de la lutte des classes",
            "OBAMA":  "44e president, premier afro-americain elu",
            "GATES":  "Fondateur d'un empire informatique mondial",
            "VINCI":  "Genie de la Renaissance aux mille talents",
            "BREL":   "Poete belge aux chansons bouleversantes",
            "NERUDA": "Poete chilien du vingtieme siecle",
        },

        "7_10": {
            "NAPOLEON":    "Exile deux fois, enterre aux Invalides",
            "EINSTEIN":    "Brevet suisse, Nobel de physique",
            "CLEOPATRE":   "Derniere pharaonne, liee a deux Romains",
            "PICASSO":     "Geometrie des visages en eclats",
            "BEETHOVEN":   "Compositions magistrales malgre le silence total",
            "VOLTAIRE":    "Plume ironique contre l'intolerance",
            "VICTOR HUGO": "Exil a Guernesey, retour en triomphe",
            "DE GAULLE":   "Appel du 18 juin, deux fois au pouvoir",
            "MANDELA":     "Vingt-sept ans de prison puis president",
            "MARADONA":    "Main gauche celeste, pied droit divin",
            "FEDERER":     "Elegance et longevite sur les courts",
            "RONALDO":     "Musculation et records de buts en club",
            "USAIN BOLT":  "Deux records du monde en finale olympique",
            "MADONNA":     "Reinvention permanente depuis quatre decennies",
            "DAVID BOWIE": "Ziggy, Aladdin Sane, identites multiples",
            "EDITH PIAF":  "Enfance dans la rue, voix qui brise les coeurs",
            "BRUCE LEE":   "Vitesse de frappe non capturable en 24 fps",
            "MIKE TYSON":  "KO en moins de deux minutes, oreille mordue",
        },
  
        "11_et_plus": {
            "SHAKESPEARE":      "Ecriture prolifique entre Londres et Stratford",
            "LEONARD DE VINCI": "Ambidextre, ingenieux, peintre et bien plus",
            "MUHAMMAD ALI":     "Refus d'aller au Vietnam, champion du monde",
            "MICHAEL JORDAN":   "Six bagues NBA avec les memes partenaires",
            "MICHAEL JACKSON":  "Moonwalk et une seule main gantee",
            "ELVIS PRESLEY":    "Graceland, hanches provocatrices, rock naissant",
            "FREDDIE MERCURY":  "Voix de cinq octaves sur scene",
            "FRANK SINATRA":    "Las Vegas, Rat Pack, chapeau incline",
            "JIMI HENDRIX":     "Guitare dans le dos, festival de Woodstock",
            "MARLON BRANDO":    "Coton dans la bouche, offre irrefusable",
            "CHARLIE CHAPLIN":  "Chapeau melon, canne et demarche chaloupee",
            "MARILYN MONROE":   "Robe blanche sur la grille de metro",
            "MERYL STREEP":     "Accent different dans chaque role marquant",
            "ZINEDINE ZIDANE":  "Coup de tete en finale, buts de volee",
            "NOVAK DJOKOVIC":   "Tous les Grand Chelem au moins deux fois",
            "AYRTON SENNA":     "Pluie, qualification pole, tragedie a Imola",
        },
    },


    "NOURRITURE": {     

        "4_6": {
            "PIZZA":  "Disque de pate, tomates et mozzarella",
            "SUSHI":  "Riz vinaigre et tranche de poisson cru",
            "FONDUE": "Fourchette longue et fromage en ebullition",
            "PAELLA": "Plat unique colore au safran",
            "TACOS":  "Galette farcie aux saveurs mexicaines",
            "CREPE":  "Fine et ronde, sucree ou salee",
            "CURRY":  "Melange d'epices mijote en sauce",
            "TRUFFE": "Champignon souterrain detecte par les cochons",
            "CAVIAR": "Oeufs noirs d'un poisson migrateur",
            "HOMARD": "Crustace a pinces, luxe des grandes tables",
            "SAUMON": "Chair rose sauvage ou d'elevage",
            "STEAK":  "Cuisson a la minute, saignant ou bien cuit",
            "ECLAIR": "Chou long glace au chocolat ou cafe",
            "KEBAB":  "Viande rotie a la broche, sauce blanche",
            "RAMEN":  "Bouillon japonais long et nouilles fines",
            "MOCHI":  "Peau de riz gluant fourree et lisse",
            "NAAN":   "Pain indien souffle au four tandoor",
        },

        "7_10": {
            "CROISSANT":   "Pate feuilletee laminee au beurre",
            "BAGUETTE":    "Craquante dehors, moelleuse dedans",
            "HAMBURGER":   "Steak hache entre deux pains brioches",
            "CHOCOLAT":    "Feve transformee par torrefaction",
            "CAMEMBERT":   "Croute blanche et coeur coulant normand",
            "FOIE GRAS":   "Mets festif du sud-ouest a tartiner",
            "ESCARGOT":    "Coquille portee, beurre persille au four",
            "TIRAMISU":    "Biscuit trempe, mascarpone et cacao",
            "LASAGNE":     "Feuilles alternees de pates et ragout",
            "RISOTTO":     "Riz nacre remue patiemment",
            "GUACAMOLE":   "Avocat ecrase aux saveurs mexicaines",
            "COUSCOUS":    "Semoule, bouillon et merguez",
            "BRIOCHE":     "Mie moelleuse enrichie de beurre et d'oeuf",
            "MACARON":     "Deux coques en amande reunies par une ganache",
            "MADELEINE":   "Bosse doree et gout de beurre noisette",
            "GAUFFRE":     "Croustillant en grille, tradition belge",
            "PARMIGIANA":  "Aubergines, tomates, fromage en couches",
            "TARTE TATIN": "Pommes caramelisees sous une croute renversee",
        },

        "11_et_plus": {
            "BOUILLABAISSE":           "Soupe de port aux poissons de roche",
            "RATATOUILLE":             "Mijoter des legumes d'ete au soleil",
            "PROFITEROLE":             "Choux farcis glaces et noyes de chocolat chaud",
            "CREME BRULEE":            "Surface cassante sous le chalumeau",
            "QUICHE LORRAINE":         "Pate brisee, lardons et appareil aux oeufs",
            "BOEUF BOURGUIGNON":       "Mijote au vin rouge avec champignons",
            "SOUPE A L'OIGNON":        "Gratinee au four dans un bol en terre",
            "MOUSSE AU CHOCOLAT":      "Blancs en neige et cacao fondu",
            "PAIN AU CHOCOLAT":        "Viennoiserie aux deux barres noires",
            "CHARLOTTE AUX FRAISES":   "Biscuits a la cuillere et mousse de fruits",
            "TARTE AU CITRON":         "Creme acide et meringue doree",
            "BLANQUETTE DE VEAU":      "Veau mijote en sauce blanche et citron",
            "SALADE NICOISE":          "Anchois, thon, oeufs durs et olives",
            "MAGRET DE CANARD":        "Poitrine de canard gras grilee",
            "GRATIN DAUPHINOIS":       "Pommes de terre fondantes en creme",
            "COQUILLES SAINT-JACQUES": "Noix de mer gratinee au beurre persille",
        },
    },

    "MUSIQUE": {           

        "4_6": {
            "JAZZ":   "Improvisation nee dans la Nouvelle-Orleans",
            "BLUES":  "Douze mesures et une peine de coeur",
            "OPERA":  "Chant lyrique et mise en scene spectaculaire",
            "PIANO":  "Touches noires et blanches sur un cadre en acier",
            "FLUTE":  "Souffle lateral dans un tube metallique",
            "PUNK":   "Trois accords et beaucoup de colere",
            "METAL":  "Guitares saturees et voix extremes",
            "SOUL":   "Voix gospel croisee au rythme urbain",
            "TANGO":  "Danse a deux qui joue avec la tension",
            "SAMBA":  "Parade carnavalesque de Rio",
            "VALSE":  "Tour sur soi en comptant jusqu'a trois",
            "SALSA":  "Clave cubaine et hanches en mouvement",
            "FOLK":   "Guitare acoustique et histoires du peuple",
            "SLAM":   "Poesie dite debout devant public",
            "HOUSE":  "Quatre-quatre et synthes de Chicago",
            "MANGA":  "Bande dessinee lue de droite a gauche",
            "CANNES": "Palme d'Or et marches en mai",
            "REGGAE": "Rythme syncopé de la Jamaique",
            "VIOLON": "Cordes frottees sous le menton",
            "GOSPEL": "Chant de foi en congregation",
            "TECHNO": "BPM eleves et basses repetitives",
            "LOUVRE": "Pyramide de verre et millions de visiteurs",
        },
  
        "7_10": {
            "SYMPHONIE":   "Quatre mouvements pour grand orchestre",
            "GUITARE":     "Six cordes pincees ou grattees",
            "BATTERIE":    "Rythme frappe sur peaux et cymbales",
            "WOODSTOCK":   "Trois jours de boue et de musique en 1969",
            "LA JOCONDE":  "Portrait a sourire ambigu dans un grand musee",
            "BAROQUE":     "Exces, courbes et dramatisme au XVIIe",
            "CUBISME":     "Plusieurs perspectives sur une seule toile",
            "COMEDIE":     "Genre theatral qui se termine bien",
            "TRAGEDIE":    "Fin fatale pour le heros",
            "FLAMENCO":    "Talon, castagnettes et cri du coeur andalou",
            "BOSSA NOVA":  "Guitare douce et voix murmuree",
            "CLASSIQUE":   "Partitions ecrites pour l'eternite",
            "ROMANTISME":  "Sentiment, nature et heroisme au XIXe",
            "ORCHESTRE":   "Ensemble de musiciens sous la baguette d'un chef",
            "ART NOUVEAU": "Courbes inspirees de la nature vers 1900",
            "DADAISME":    "Mouvement anti-art ne dans la guerre",
            "STREET ART":  "Art urbain dans l'espace public",
            "PALME D'OR":  "Recompense supreme du festival de Cannes",
        },

        "11_et_plus": {
            "IMPRESSIONNISME":   "Touche visible et lumiere du moment",
            "RENAISSANCE":       "Retour a l'Antiquite en peinture et sculpture",
            "SURREALISME":       "Reves et inconscient en peinture",
            "CHANSON FRANCAISE": "Poesie et melodie, de Brel a Gainsbourg",
            "COMEDIE MUSICALE":  "Chant et danse au service d'une histoire",
            "EXPRESSIONNISME":   "Deformation du reel pour exprimer l'interieur",
            "NATURALISME":       "Realite crue dans la litterature du XIXe",
            "CHAPELLE SIXTINE":  "Plafond peint en quatre ans en levant la tete",
            "CLASSICISME":       "Ordre, raison et beaute ideale au XVIIe",
            "CONSERVATOIRE":     "Ecole superieure pour musiciens et comediens",
            "GRAMMY AWARDS":     "Ceremonie americaine de recompenses musicales",
        },
    },


    "SPORT": {           

        "4_6": {
            "BOXE":   "Garde haute, jab et crochet du gauche",
            "JUDO":   "Projection au sol et immobilisation",
            "GOLF":   "Moins de coups pour dix-huit trous",
            "SURF":   "Equilibre sur une planche en mouvement",
            "RUGBY":  "Ballon ovale porte vers l'en-but",
            "TENNIS": "Filet, raquette et balles jaunes",
            "VOLLEY": "Six joueurs, pas le droit de tenir le ballon",
            "AVIRON": "Synchronisation de rameurs et un barreur",
            "KARATE": "Katas et combats codifies",
            "DERBY":  "Rivalite locale entre deux clubs voisins",
            "PODIUM": "Trois marches et une medaille",
            "DOPAGE": "Substances interdites pour ameliorer les performances",
            "LIBERO": "Joueur defensif sans droit d'attaquer au volley",
            "PIVOT":  "Joueur dos au panier au basketball",
            "MELEE":  "Affrontement de packs au rugby",
            "CHRONO": "Course contre la montre individuelle",
            "SPRINT": "Effort maximal sur courte distance",
        },

        "7_10": {
            "FOOTBALL":   "Onze contre onze, un ballon rond",
            "BASKETBALL": "Panier a trois metres de hauteur",
            "NATATION":   "Quatre nages, un bassin de cinquante metres",
            "CYCLISME":   "Peloton, echappee et sprint final",
            "ESCRIME":    "Touche electrique et masque grillage",
            "SKI ALPIN":  "Descente sur neige a grande vitesse",
            "HANDBALL":   "But a la main, gardien et pivot",
            "FORMULE 1":  "Aerodynamisme et strategie pneumatique",
            "MARATHON":   "Quarante-deux kilometres et des poussieres",
            "TRIATHLON":  "Trois disciplines sans interruption",
            "ESCALADE":   "Murs artificiels ou falaises naturelles",
            "TAEKWONDO":  "Coups de pied cibles sur un plastron electronique",
            "SUPER BOWL": "Show de mi-temps et finale americaine",
            "WIMBLEDON":  "Blanc obligatoire et fraises a la creme",
            "HAT TRICK":  "Troisieme but du meme joueur dans un match",
            "PENALTY":    "Face au gardien, point de onze metres",
            "PRESSING":   "Recuperation haute et pression constante",
            "ATHLETISME": "Piste ovale, sable et secteur de lancer",
            "EQUITATION": "Dressage, saut d'obstacles et cross",
            "TRANSFERT":  "Passage d'un joueur d'un club a un autre",
            "PALMARES":   "Liste des titres accumules au fil des annees",
            "ARBITRE":    "Celui qui fait respecter les regles sur le terrain",
        },

        "11_et_plus": {
            "HALTEROPHILIE":       "Arracher ou epauler-jeter le plus lourd",
            "GYMNASTIQUE":         "Barre fixe, sol et note d'execution",
            "ROLAND GARROS":       "Ocre et balles plus lentes",
            "TOUR DE FRANCE":      "Maillot jaune, montagne et paves",
            "LIGUE DES CHAMPIONS": "Hymne et etoiles europeennes",
            "COUPE DU MONDE":      "Trophee dore leve tous les quatre ans",
            "JEUX OLYMPIQUES":     "Anneaux et flamme tous les quatre ans",
            "CARTON ROUGE":        "Sortie immediate et definitive",
            "CLASSEMENT ATP":      "Points accumules sur douze mois au tennis",
            "CONTRE ATTAQUE":      "Transition rapide de la defense a l'attaque",
            "HUITIEME DE FINALE":  "Premier tour eliminatoire des grandes competitions",
            "RECORD DU MONDE":     "Marque jamais atteinte auparavant dans la discipline",
        },
    },


    "SCIENCES": {           

  
        "4_6": {
            "ATOME":  "Noyau entoure d'un nuage electronique",
            "PHOTON": "Particule sans masse a vitesse maximale",
            "QUARK":  "Constituant interne des protons et neutrons",
            "MARS":   "Quatrieme planete, cible d'exploration robotique",
            "COMETE": "Noyau de glace et trainees lumineuses",
            "VACCIN": "Entrainement du systeme immunitaire",
            "FUSION": "Deux noyaux legers qui liberent de l'energie",
            "NEWTON": "Pomme, inertie et lois du mouvement",
            "TESLA":  "Courant alternatif contre Edison",
            "MENDEL": "Pois, hybrides et lois de l'heredite",
            "GENOME": "Ensemble complet du materiel genetique",
            "CLONE":  "Copie genetique identique d'un organisme",
            "ENZYME": "Catalyseur biologique d'une reaction chimique",
            "PLASMA": "Quatrieme etat de la matiere a haute temperature",
            "LASER":  "Lumiere coherente et amplifiee",
            "PROTON": "Particule chargee positivement dans le noyau",
            "ACIDE":  "Substance au pH inferieur a 7",
        },
  
        "7_10": {
            "RELATIVITE":  "Espace et temps lies par la vitesse",
            "EVOLUTION":   "Variation, selection et temps geologique",
            "ELECTRON":    "Charge negative gravitant autour du noyau",
            "TROU NOIR":   "Courbure infinie de l'espace-temps",
            "BIG BANG":    "Expansion depuis une singularite initiale",
            "GALAXIE":     "Milliards d'etoiles liees par la gravite",
            "JUPITER":     "Geante gazeuse aux aurores polaires intenses",
            "SATURNE":     "Anneaux de glace et de roches en orbite",
            "ASTEROIDE":   "Debris rocheux en orbite autour du Soleil",
            "FISSION":     "Noyau lourd brise en deux plus de l'energie",
            "CHROMOSOME":  "Bobine d'ADN dans le noyau cellulaire",
            "CELLULE":     "Unite structurale et fonctionnelle du vivant",
            "MARIE CURIE": "Deux Nobel, polonaise travaillant a Paris",
            "PASTEUR":     "Fermentation, microbes et premiere rage guerie",
            "ARCHIMEDE":   "Corps immerge, volume deplace et poussee",
            "GALILEE":     "Telescope pointe vers Jupiter et condamne",
            "HEISENBERG":  "Position et vitesse impossibles a mesurer ensemble",
            "COPERNIC":    "Modele heliocentrique contre l'Eglise",
            "NIELS BOHR":  "Modele planetaire de l'atome en 1913",
            "FARADAY":     "Bobine, aimant et induction electromagnetique",
            "TROU DE VER": "Tunnel hypothetique entre deux points de l'espace",
        },
        "11_et_plus": {
            "GRAVITATION":               "Force proportionnelle aux masses",
            "PENICILLINE":               "Moisissure qui a change la medecine",
            "RADIOACTIVITE":             "Desintegration spontanee d'un noyau instable",
            "PHOTOSYNTHESE":             "Lumiere et CO2 transformes en sucre et oxygene",
            "STEPHEN HAWKING":           "Rayonnement des trous noirs depuis un fauteuil",
            "ANTIBIOTIQUE":              "Molecule bactericide issue de champignons",
            "SUPRACONDUCTEUR":           "Resistance electrique nulle sous un certain seuil",
            "THEORIE DES CORDES":        "Onze dimensions et vibrations fondamentales",
            "SELECTION NATURELLE":       "Survie des mieux adaptes au milieu",
            "ENERGIE SOMBRE":            "Force inconnue qui accelere l'expansion de l'univers",
            "MATIERE NOIRE":             "Masse invisible qui tient les galaxies ensemble",
            "INTELLIGENCE ARTIFICIELLE": "Simulation de raisonnement par une machine",
            "CHROMOSOME X":              "Chromosome determinant le sexe chez les mammiferes",
        },
    },


    "HISTOIRE": {           

        "4_6": {
            "SHOAH":  "Six millions de morts dans le systeme nazi",
            "GAULE":  "Territoire d'avant la France romaine",
            "ROME":   "Capitale d'un empire milleneaire",
            "GRECE":  "Berceau de la democratie et de la philosophie",
            "TRAITE": "Accord signe entre deux nations ennemies",
            "EXIL":   "Eloignement force d'un territoire",
            "SIEGE":  "Encerclement militaire d'une ville",
            "BLOCUS": "Couper les approvisionnements d'une zone",
            "TYRAN":  "Dirigeant qui gouverne par la terreur",
            "SERF":   "Paysan lie a la terre du seigneur",
            "VOTE":   "Acte fondateur de la democratie",
            "PURGE":  "Elimination systematique d'opposants",
            "DECRET": "Texte de loi emanant du pouvoir executif",
            "TREVE":  "Arret temporaire des combats",
            "CHARTE": "Texte fondateur de droits essentiels",
            "GILDE":  "Corporation de marchands ou d'artisans au Moyen Age",
            "DUCHE":  "Territoire gouverne par un duc",
        },
  
        "7_10": {
            "BASTILLE":    "Forteresse parisienne symbole d'un regime",
            "WATERLOO":    "Defaite qui mit fin a cent jours de retour",
            "VERSAILLES":  "Traite signe dans la galerie des glaces",
            "AUSCHWITZ":   "Le plus grand des camps d'extermination",
            "HIROSHIMA":   "Premiere detonation nucleaire sur une ville",
            "STALINGRAD":  "Siege et bataille qui tourna la guerre a l'est",
            "CROISADES":   "Expeditions armees vers la Terre sainte",
            "ESCLAVAGE":   "Commerce triangulaire et deshumanisation",
            "ABOLITION":   "Fin legale d'une pratique injuste",
            "CENSURE":     "Controle officiel des contenus diffuses",
            "PROPAGANDE":  "Information orientee au service du pouvoir",
            "RESISTANCE":  "Lutte clandestine sous l'occupation nazie",
            "GENOCIDE":    "Extermination planifiee d'un groupe humain",
            "COUP D'ETAT": "Prise de pouvoir brutale et illegale",
            "APARTHEID":   "Segregation legale en Afrique du Sud",
            "CAPITOLE":    "Colline sacree et siege du Senat romain",
            "CROISADE":    "Expedition armee au nom de la foi chretienne",
        },

        "11_et_plus": {
            "PEARL HARBOR":            "Attaque surprise qui fit basculer une guerre",
            "INQUISITION":             "Tribunal religieux qui chassait l'heresie",
            "COLONISATION":            "Conquete et administration de terres etrangeres",
            "CONSTITUTION":            "Loi supreme qui fonde un etat",
            "DEPORTATION":             "Transfert force vers les camps de la mort",
            "REVOLUTION FRANCAISE":    "Trois couleurs et une tete de roi tombee",
            "REVOLUTION INDUSTRIELLE": "Charbon, acier et exode rural",
            "EMPIRE ROMAIN":           "Legions, routes et droit sur tout le bassin",
            "GUERRE DE CENT ANS":      "Jeanne d'Arc, Azincourt et deux couronnes",
            "SIECLE DES LUMIERES":     "Raison, encyclopedie et critique du pouvoir",
            "REVOLUTION AMERICAINE":   "Boston, independance et premiere republique moderne",
            "AFFAIRE DREYFUS":         "Proces injuste et fracture de la societe francaise",
            "GUERRE FROIDE":           "Deux blocs, course aux armements, pas de guerre directe",
            "DECOLONISATION":          "Independances en serie dans les annees 50 et 60",
            "TRAITE DE MAASTRICHT":    "Naissance officielle de l'Union europeenne",
            "BATAILLE DE VERDUN":      "Enfer de boue et d'obus en 1916",
            "PRISE DE CONSTANTINOPLE": "Fin d'un empire, debut d'un autre en 1453",
        },
    },

    "EVENEMENTS": {           

        "4_6": {
            "COVID":  "Confinements et masques sur toute la planete",
            "BREXIT": "Referendum britannique et sortie de l'Union",
            "KRACH":  "Effondrement brutal des marches financiers",
            "EXODE":  "Deplacement massif d'une population en fuite",
            "POGROM": "Violence organisee contre une minorite",
            "SIEGE":  "Encerclement total d'une ville en guerre",
            "PURGE":  "Elimination massive d'opposants politiques",
            "CHUTE":  "Effondrement soudain d'un regime ou d'un mur",
            "GREVE":  "Arret collectif du travail pour revendiquer",
            "EMEUTE": "Soulevement spontane et violent dans la rue",
            "TREVE":  "Suspension temporaire d'un conflit arme",
            "RAID":   "Attaque surprise sur un objectif militaire",
            "CRISE":  "Periode de forte instabilite economique ou politique",
            "BLOCUS": "Isolement total d'une zone par encerclement",
            "PUTSCH": "Tentative de coup de force contre un gouvernement",
            "FUITE":  "Abandon precipite d'une position ou d'un pays",
            "PACTE":  "Accord secret entre deux puissances",
        },
        # 11 mots | 7 a 10 lettres
        "7_10": {
            "TCHERNOBYL": "Reacteur quatre explose en Ukraine sovietique",
            "FUKUSHIMA":  "Seisme, tsunami et reacteur nucleaire endommage",
            "TSUNAMI":    "Vague geante declenchee par un seisme sous-marin",
            "ARMISTICE":  "Fin officielle des combats de la Grande Guerre",
            "MIGRATION":  "Mouvement massif de populations vers d'autres regions",
            "LIBERATION": "Fin d'une occupation militaire etrangere",
            "BARRICADE":  "Obstacle improvise dans les rues en revolte",
            "OFFENSIVE":  "Attaque militaire de grande ampleur",
            "PARTITION":  "Division d'un territoire en deux entites",
            "REVOLUTION": "Renversement radical d'un systeme politique",
            "SABOTAGE":   "Destruction deliberee d'une infrastructure ennemie",
        },
        "11_et_plus": {
            "CAPITULATION":             "Reddition militaire officielle et totale",
            "INSURRECTION":             "Soulevement arme contre le pouvoir en place",
            "DEBARQUEMENT":             "Troupes qui prennent pied sur une plage ennemie",
            "BOMBARDEMENT":             "Attaque aerienne ou d'artillerie prolongee",
            "MOBILISATION":             "Appel aux armes d'une population entiere",
            "SOULEVEMENT":              "Mouvement populaire contre une autorite",
            "ATTENTAT DU 11 SEPTEMBRE": "Tours jumelles et monde bascule",
            "CHUTE DU MUR DE BERLIN":   "Novembre 1989, beton ebranlé dans la nuit",
            "ERUPTION DE POMPEI":       "Ville ensevelie sous les cendres du Vesuve",
            "CYCLONE KATRINA":          "Nouvelle-Orleans submergee et abandonnee",
            "FEU DE NOTRE-DAME":        "Fleche effondree et emotion mondiale en 2019",
            "FAMINE EN IRLANDE":        "Mildiou, emigration massive et depopulation",
            "SOMMET DE YALTA":          "Trois grands et partage du monde d'apres-guerre",
            "PREMIER VOL MOTORISE":     "Kitty Hawk, douze secondes, histoire changee",
            "CRISE DES MISSILES":       "Treize jours au bord de la guerre nucleaire",
            "MASSACRE DE TIANANMEN":    "Char face a un homme seul, image mondiale",
            "GENOCIDE RWANDAIS":        "Cent jours, un million de morts en 1994",
            "GUERRE DU GOLFE":          "Coalition internationale contre l'invasion du Koweit",
            "REVOLUTION CUBAINE":       "Barbu descendu des montagnes et ile transformee",
            "LANCEMENT D'INTERNET":     "ARPANET et le premier message envoye en 1969",
            "REUNIFICATION ALLEMANDE":  "Un seul passeport pour une seule nation en 1990",
            "PRINTEMPS DE PRAGUE":      "Reformes ecrasees par les chars sovietiques",
            "ASSASSINAT DE KENNEDY":    "Dallas, 1963, cabriolet et balles",
        },
    },

}
